Repository wazo-platform/wazo-confd, pull requests merged in 2020-10, with the labels that each got.

#159 sed s/wazopbx/wazoplatform/
  integration_tests/Dockerfile
  integration_tests/Makefile
  integration_tests/assets/docker-compose.wizard.override.yml
  integration_tests/assets/docker-compose.yml
  integration_tests/suite/helpers/provd.py
Labels: auto-merge, mergeit

#158 cli: fix arguement --profile
  wazo_confd/config.py
Labels: mergeit

#160 improve incall-queue tests to avoid label to None
  integration_tests/suite/base/test_incalls.py
Labels: auto-merge, mergeit

#161 Pull request for WAZO-2041-external-app-tenant
  CHANGELOG.md
  integration_tests/suite/base/test_external_apps.py
  integration_tests/suite/helpers/fixtures.py
  integration_tests/suite/helpers/helpers/__init__.py
  integration_tests/suite/helpers/helpers/external_app.py
  setup.py
  wazo_confd/config.py
  wazo_confd/plugins/external_app/__init__.py
  wazo_confd/plugins/external_app/api.yml
  wazo_confd/plugins/external_app/notifier.py
  wazo_confd/plugins/external_app/plugin.py
  wazo_confd/plugins/external_app/resource.py
  wazo_confd/plugins/external_app/schema.py
  wazo_confd/plugins/external_app/service.py
  wazo_confd/plugins/external_app/tests/__init__.py
  wazo_confd/plugins/external_app/tests/test_notifier.py
  wazo_confd/plugins/external_app/validator.py
  wazo_confd/plugins/incall/validator.py
Labels: mergeit

#164 registrar: fix offset/limit query
  integration_tests/suite/base/test_registrars.py
  wazo_confd/plugins/registrar/dao.py
Labels: mergeit

#165 Wazo 2043 external app fallback
  integration_tests/suite/base/test_user_external_apps.py
  wazo_confd/plugins/endpoint_sip/api.yml
  wazo_confd/plugins/user_external_app/api.yml
  wazo_confd/plugins/user_external_app/resource.py
  wazo_confd/plugins/user_external_app/schema.py
  wazo_confd/plugins/user_external_app/service.py
Labels: auto-merge

#166 bump kombu version to 4.6.11
  requirements.txt
Labels: auto-merge, mergeit
