Repository wazo-platform/wazo-confd, pull requests merged in 2021-03, with the labels that each got.

#186 Pull request for WAZO-2124-restrict-master-tenant-resources
  CHANGELOG.md
  integration_tests/suite/base/__init__.py
  integration_tests/suite/base/test_access_features.py
  integration_tests/suite/base/test_auth.py
  integration_tests/suite/base/test_confbridge_wazo_default_bridge.py
  integration_tests/suite/base/test_confbridge_wazo_default_user.py
  integration_tests/suite/base/test_configuration.py
  integration_tests/suite/base/test_dhcp.py
  integration_tests/suite/base/test_extensions_features.py
  integration_tests/suite/base/test_features_applicationmap.py
  integration_tests/suite/base/test_features_featuremap.py
  integration_tests/suite/base/test_features_general.py
  integration_tests/suite/base/test_ha.py
  integration_tests/suite/base/test_hep_general.py
  integration_tests/suite/base/test_iax_callnumberlimits.py
  integration_tests/suite/base/test_iax_general.py
  integration_tests/suite/base/test_pjsip_global.py
  integration_tests/suite/base/test_pjsip_system.py
  integration_tests/suite/base/test_pjsip_transports.py
  integration_tests/suite/base/test_provisioning_networking.py
  integration_tests/suite/base/test_queues_general.py
  integration_tests/suite/base/test_registrars.py
  integration_tests/suite/base/test_rtp_general.py
  integration_tests/suite/base/test_rtp_ice_host_candidates.py
  integration_tests/suite/base/test_sccp_general.py
  integration_tests/suite/base/test_voicemail_general.py
  integration_tests/suite/base/test_voicemail_zonemessages.py
  integration_tests/suite/helpers/base.py
  integration_tests/suite/helpers/client.py
  integration_tests/suite/helpers/config.py
  integration_tests/suite/helpers/helpers/__init__.py
  wazo_confd/auth.py
  wazo_confd/controller.py
  wazo_confd/helpers/restful.py
  wazo_confd/plugins/access_feature/resource.py
  wazo_confd/plugins/confbridge/resource.py
  wazo_confd/plugins/configuration/resource.py
  wazo_confd/plugins/dhcp/resource.py
  wazo_confd/plugins/extension_feature/resource.py
  wazo_confd/plugins/features/resource.py
  wazo_confd/plugins/ha/resource.py
  wazo_confd/plugins/ha/service.py
  wazo_confd/plugins/hep/resource.py
  wazo_confd/plugins/iax_callnumberlimits/resource.py
  wazo_confd/plugins/iax_general/resource.py
  wazo_confd/plugins/pjsip/resource.py
  wazo_confd/plugins/provisioning_networking/resource.py
  wazo_confd/plugins/queue_general/resource.py
  wazo_confd/plugins/registrar/resource.py
  wazo_confd/plugins/rtp/resource.py
  wazo_confd/plugins/sccp_general/resource.py
  wazo_confd/plugins/voicemail_general/resource.py
  wazo_confd/plugins/voicemail_zonemessages/resource.py
Labels: mergeit

#188 send registration_section_options in sip events
  wazo_confd/plugins/endpoint_sip/notifier.py
  wazo_confd/plugins/endpoint_sip/tests/test_notifier.py
Labels: mergeit

#187 moh: deprecate mp3
  wazo_confd/plugins/moh/api.yml
Labels: mergeit

#185 Wazo 2246 group UUID
  CHANGELOG.md
  integration_tests/suite/base/test_group_call_permission.py
  integration_tests/suite/base/test_group_extension.py
  integration_tests/suite/base/test_group_fallback.py
  integration_tests/suite/base/test_group_member_extension.py
  integration_tests/suite/base/test_group_member_user.py
  integration_tests/suite/base/test_group_schedule.py
  integration_tests/suite/base/test_groups.py
  integration_tests/suite/helpers/associations.py
  integration_tests/suite/helpers/fixtures.py
  integration_tests/suite/helpers/helpers/group_extension.py
  wazo_confd/plugins/call_permission/schema.py
  wazo_confd/plugins/extension/schema.py
  wazo_confd/plugins/group/api.yml
  wazo_confd/plugins/group/notifier.py
  wazo_confd/plugins/group/plugin.py
  wazo_confd/plugins/group/resource.py
  wazo_confd/plugins/group/schema.py
  wazo_confd/plugins/group/tests/test_notifier.py
  wazo_confd/plugins/group_call_permission/api.yml
  wazo_confd/plugins/group_call_permission/notifier.py
  wazo_confd/plugins/group_call_permission/plugin.py
  wazo_confd/plugins/group_call_permission/resource.py
  wazo_confd/plugins/group_call_permission/tests/test_notifier.py
  wazo_confd/plugins/group_extension/api.yml
  wazo_confd/plugins/group_extension/notifier.py
  wazo_confd/plugins/group_extension/plugin.py
  wazo_confd/plugins/group_extension/resource.py
  wazo_confd/plugins/group_extension/tests/test_notifier.py
  wazo_confd/plugins/group_fallback/api.yml
  wazo_confd/plugins/group_fallback/notifier.py
  wazo_confd/plugins/group_fallback/plugin.py
  wazo_confd/plugins/group_fallback/resource.py
  wazo_confd/plugins/group_fallback/tests/test_notifier.py
  wazo_confd/plugins/group_member/api.yml
  wazo_confd/plugins/group_member/notifier.py
  wazo_confd/plugins/group_member/plugin.py
  wazo_confd/plugins/group_member/resource.py
  wazo_confd/plugins/group_member/tests/test_notifier.py
  wazo_confd/plugins/group_schedule/api.yml
  wazo_confd/plugins/group_schedule/notifier.py
  wazo_confd/plugins/group_schedule/plugin.py
  wazo_confd/plugins/group_schedule/resource.py
  wazo_confd/plugins/group_schedule/tests/test_notifier.py
  wazo_confd/plugins/group_schedule/validator.py
  wazo_confd/plugins/schedule/schema.py
  wazo_confd/plugins/user/api.yml
  wazo_confd/plugins/user/schema.py
Labels: mergeit

#189 sed XiVO/Wazo
  wazo_confd/plugins/user/api.yml
  wazo_confd/plugins/wizard/access_restriction.py
  wazo_confd/plugins/wizard/resource.py
Labels: auto-merge, mergeit

#191 recording: remove the recording warning
  wazo_confd/plugins/user/api.yml
Labels: mergeit

#190 Pull request for WAZO-2292-email-config
  CHANGELOG.md
  integration_tests/suite/base/test_emails.py
  setup.py
  tox.ini
  wazo_confd/config.py
  wazo_confd/database/email.py
  wazo_confd/plugins/email/__init__.py
  wazo_confd/plugins/email/api.yml
  wazo_confd/plugins/email/notifier.py
  wazo_confd/plugins/email/plugin.py
  wazo_confd/plugins/email/resource.py
  wazo_confd/plugins/email/schema.py
  wazo_confd/plugins/email/service.py
  wazo_confd/plugins/email/tests/__init__.py
  wazo_confd/plugins/email/tests/test_notifier.py
  wazo_confd/plugins/email/tests/test_schema.py
Labels: mergeit

#192 WAZO-1552: rename xivo-sysconfd to wazo-sysconfd
  etc/wazo-confd/config.yml
Labels: auto-merge, mergeit

#194 CHANGELOG: fix styling issue
  CHANGELOG.md
Labels: auto-merge
